In [2]:
import numpy as np
n=int(input("Enter number of unknown"))
col=[]
for i in range(0,n):
    row = []
    for j in range(0,n+1):
        print("Enter A",i,j)
        temp=float(input())
        row.append(temp)
    col.append(row)
A=np.matrix(col)
print(A)

input()
for i in range(0,n):
    for j in range(0,n):
        A[i,:]=A[i,:]/A[i,i]
        if i!=j:
            factor=A[j,i]/A[i,i]
            for k in range(0,n+1):
                A[j,k]=A[j,k]-factor*A[i,k]
print(A)
print(A[:,n])
    

Enter number of unknown2
Enter A 0 0
3
Enter A 0 1
7
Enter A 0 2
9
Enter A 1 0
8
Enter A 1 1
5
Enter A 1 2
5
[[3. 7. 9.]
 [8. 5. 5.]]
2
[[ 1.          0.         -0.24390244]
 [-0.          1.          1.3902439 ]]
[[-0.24390244]
 [ 1.3902439 ]]


## 